import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Badge, PageIntro, SectionHeading, SourceLine } from '@/components/site';
import { evidenceData, getLinkStatus, getProjectResourceState } from '@/lib/content/evidence';
import { siteData } from '@/lib/content';
import { getPathwayArtifact } from '@/lib/content/repository';
import { siteConfig } from '@/lib/site-config';

const linkStatusLabels = { available: '入口可访问', degraded: '入口有变化', unavailable: '入口不可用', unverified: '入口待复核' } as const;

export function generateStaticParams() { return siteData.projects.map((project) => ({ projectSlug: project.slug })); }

export function generateMetadata({ params }: { params: { projectSlug: string } }): Metadata {
  const project = siteData.projects.find((item) => item.slug === params.projectSlug);
  return { title: project?.title ?? '项目体验卡', description: project?.summary ?? 'HseeHub 项目体验卡', alternates: { canonical: `/projects/${params.projectSlug}` } };
}

export default function ProjectDetailPage({ params }: { params: { projectSlug: string } }) {
  const project = siteData.projects.find((item) => item.slug === params.projectSlug);
  if (!project) notFound();
  const majorMap = new Map(siteData.majors.map((major) => [major.id, major]));
  const source = siteData.sources.find((item) => item.id === project.sourceId);
  const previewSource = siteData.sources.find((item) => item.id === project.preview.sourceRef);
  const artifact = getPathwayArtifact(project.artifactId);
  const resourceState = getProjectResourceState(project);
  const needsReview = project.reviewDueAt < new Date().toISOString().slice(0, 10);
  const endpoints = evidenceData.endpoints.filter((endpoint) => project.endpointIds.includes(endpoint.id));
  const capabilityLabels = project.capabilityIds.map((id) => siteData.capabilities.find((item) => item.id === id)?.shortName).filter(Boolean);
  const scenarioLabels = project.scenarioIds.map((id) => siteData.scenarios.find((item) => item.id === id)?.name).filter(Boolean);
  const courseEvidence = project.courseEvidence.map((evidence) => ({ ...evidence, major: majorMap.get(evidence.majorId) }));
  return <>
    <section className="project-hero"><div className="page-container"><div className="breadcrumb"><Link href="/projects">做个项目</Link><span aria-hidden="true">/</span><span>{project.title}</span></div><div className="project-hero-content"><Badge tone={project.majorIds.length > 1 ? 'amber' : 'teal'}>{project.kicker}</Badge><h1>{project.title}</h1><p>{project.summary}</p><div className="tag-row">{project.majorIds.map((id) => <Badge key={id} tone="muted">{majorMap.get(id)?.shortName}</Badge>)}<Badge tone="muted">{project.viewpoint}</Badge>{capabilityLabels.map((label) => <Badge key={label}>{label}</Badge>)}</div>{needsReview ? <div className="review-notice" role="status"><strong>需要复核</strong><span>这张项目卡已过复核日期，开始前请重新打开资源入口和许可说明。</span></div> : null}</div><div className="project-facts"><div className="project-fact"><span>适合谁</span><strong>{project.suitableFor}</strong></div><div className="project-fact"><span>预计时长</span><strong>{project.duration}</strong></div><div className="project-fact"><span>开始前需要</span><strong>{project.prerequisites.join('；')}</strong></div><div className="project-fact"><span>资源状态</span><strong className={`resource-state resource-state-${resourceState.key}`}><span aria-hidden="true">{resourceState.key === 'ready' ? '●' : resourceState.key === 'alternative' ? '↗' : '!'}</span>{resourceState.label}</strong></div></div></div></section>
    <div className="page-container"><section className="detail-block"><div className="detail-layout"><div className="reading-column"><SectionHeading eyebrow="01 / 开始条件" title="开始条件：先知道自己要做什么，做到哪一步可以停" /><p>{project.summary}</p><div className="card-grid card-grid-2 section-gap-top"><article className="side-card"><strong>最低基础</strong><ul className="detail-list list-no-top">{project.prerequisites.map((item) => <li key={item}>{item}</li>)}</ul></article><article className="side-card"><strong>这次会练什么</strong><p>{capabilityLabels.join('、')}</p><p>{scenarioLabels.join('、')}</p></article></div><SectionHeading eyebrow="02 / 步骤" title="步骤：把一次小尝试拆成可复核的几步" /><ol className="project-step-list">{project.steps.map((step) => <li key={step}>{step}</li>)}</ol><div className="boundary-card section-gap-top"><strong>停止条件</strong><p>{project.stopCondition}</p></div></div><aside className="side-panel"><div className="side-card"><strong>先看资源状态</strong><p>{resourceState.description}</p><Link className="text-link" href={`/projects/${project.slug}/resources`}>查看主入口和替代入口 <span aria-hidden="true">↗</span></Link></div><div className="boundary-card"><strong>风险边界</strong><p>{project.boundary}</p></div></aside></div></section>
      <section className="detail-block" id="artifact-template"><SectionHeading eyebrow="03 / 产物模板" title="产物模板：把过程、结果和限制放在同一份记录里" description="产物由你自己保存；本站不要求上传作品，也不把一次示例结果当成结论。" /><div className="project-artifact-layout"><div className="project-artifact-preview"><img src={project.preview.src} alt={project.preview.alt} width="560" height="360" /><p className="asset-note">预览说明：{project.preview.author} · {project.preview.license} · 来源：{previewSource?.title ?? project.preview.sourceRef} · {project.preview.generationRef}</p></div><div className="project-artifact-info"><Badge tone="blue">{artifact?.title ?? project.expectedOutput}</Badge><h3>{project.expectedOutput}</h3><p>{artifact?.description ?? '记录问题、步骤、结果、误差和限制。'}</p><dl className="artifact-facts"><div><dt>模板版本</dt><dd>{project.artifactTemplate.version}</dd></div><div><dt>许可</dt><dd>{project.artifactTemplate.license}</dd></div><div><dt>复盘问题</dt><dd>{project.reflectionPrompt}</dd></div></dl><a className="button button-secondary" href={project.artifactTemplate.href} download>{project.artifactTemplate.label} <span aria-hidden="true">↓</span></a></div></div><div className="callout"><p><strong>验收：</strong>{project.validation}</p></div></section>
      {project.mode === 'cross-major' ? <section className="detail-block"><SectionHeading eyebrow="04 / 协作接口" title="两种专业怎样交接输入、输出和验收" description="角色只是能力匹配建议，不限制学生跨专业承担任务，也不等同于就业岗位。" /><div className="card-grid card-grid-2">{project.collaborationRoles.map((role) => <article className="side-card" key={role.id}><Badge tone={role.suggestedMajorIds.includes('major-bme') ? 'teal' : 'blue'}>{role.title}</Badge><p><strong>职责：</strong>{role.responsibilities.join('；')}</p><p><strong>输入：</strong>{role.inputs.join('；')}</p><p><strong>输出：</strong>{role.outputs.join('；')}</p><p><strong>验收：</strong>{role.acceptance.join('；')}</p></article>)}</div></section> : null}
      <section className="detail-block"><SectionHeading eyebrow={project.mode === 'cross-major' ? '05 / 数据许可' : '04 / 数据许可'} title="数据许可：打开外部教程前，先核对这些信息" /><div className="comparison-table-wrap"><table className="comparison-table"><caption className="sr-only">项目工具、数据和许可</caption><tbody><tr><th scope="row">工具 / 材料</th><td><ul className="detail-list list-no-top">{project.tools.map((tool) => <li key={tool.name}><a className="text-link" href={tool.officialUrl} target="_blank" rel="noreferrer">{tool.name} <span aria-hidden="true">↗</span></a></li>)}</ul></td></tr><tr><th scope="row">数据类型</th><td>{siteConfig.projectDataLabels.kind[project.data.kind]} · {siteConfig.projectDataLabels.sensitivity[project.data.sensitivity]}</td></tr><tr><th scope="row">数据访问</th><td>{project.dataAccess}（{siteConfig.projectDataLabels.access[project.data.access]}）</td></tr><tr><th scope="row">数据来源</th><td>{project.dataSource}</td></tr><tr><th scope="row">许可</th><td>{project.license}</td></tr></tbody></table></div></section>
      <section className="detail-block"><SectionHeading eyebrow={project.mode === 'cross-major' ? '06 / 下一步' : '05 / 下一步'} title="下一步：如果继续，先学什么、先确认什么" /><div className="card-grid card-grid-2"><article className="side-card"><strong>继续做什么</strong><p>{project.nextStep}</p></article><article className="side-card"><strong>主入口和替代入口</strong><div className="endpoint-list">{endpoints.map((endpoint) => <div className="endpoint-row" key={endpoint.id}><span>{endpoint.role === 'source' ? '主入口' : '替代入口'}</span><span className={`resource-state resource-state-${getLinkStatus(endpoint.id) === 'available' ? 'ready' : getLinkStatus(endpoint.id) === 'unavailable' ? 'unavailable' : 'unknown'}`}>{linkStatusLabels[getLinkStatus(endpoint.id)]}</span><a className="text-link" href={endpoint.url} target="_blank" rel="noreferrer">打开 <span aria-hidden="true">↗</span></a></div>)}</div></article></div><div className="source-block-spaced"><SourceLine source={source} label="项目来源" /></div></section>
    </div>
  </>;
}
