import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getProjectDetailModel, siteData } from '@/lib/content';
import { siteConfig } from '@/lib/site-config';
import { ArrowLink, Badge, PageIntro, SectionHeading, SourceLine } from '@/components/site';
import { StatusBadge } from '@/components/ui/primitives';

export function generateStaticParams() { return siteData.projects.map((project) => ({ projectSlug: project.slug })); }

export function generateMetadata({ params }: { params: { projectSlug: string } }): Metadata {
  const project = siteData.projects.find((item) => item.slug === params.projectSlug);
  return { title: project?.title ?? '项目体验卡', description: project?.summary ?? 'HseeHub 项目体验卡', alternates: { canonical: `/projects/${params.projectSlug}` } };
}

export default function ProjectDetailPage({ params }: { params: { projectSlug: string } }) {
  const project = siteData.projects.find((item) => item.slug === params.projectSlug);
  if (!project) notFound();
  const model = getProjectDetailModel(params.projectSlug);
  if (!model) notFound();
  const majorMap = new Map(siteData.majors.map((major) => [major.id, major]));
  const source = siteData.sources.find((item) => item.id === project.sourceId);
  const capabilityLabels = model.capabilities.filter(Boolean);
  const scenarioLabels = model.scenarios.filter(Boolean);
  const courseEvidence = project.courseEvidence.map((evidence) => ({ ...evidence, major: majorMap.get(evidence.majorId) }));
  return <>
    <section className="project-hero"><div className="page-container"><div className="breadcrumb"><Link href="/projects">项目探索</Link><span aria-hidden="true">/</span><span>{project.title}</span></div><div className="project-hero-content"><Badge tone={project.majorIds.length > 1 ? 'amber' : 'teal'}>{project.kicker}</Badge><h1>{project.title}</h1><p>{project.summary}</p><div className="tag-row">{model.majors.map((major) => major ? <Link className="badge badge-muted badge-link" key={major.id} href={`/majors/${major.slug}`}>{major.shortName}</Link> : null)}<Badge tone="muted">{project.viewpoint}</Badge>{capabilityLabels.map((capability) => capability ? <Link className="badge badge-muted badge-link" key={capability.id} href={`/capabilities/${capability.slug}`}>{capability.shortName}</Link> : null)}{scenarioLabels.slice(0, 2).map((scenario) => scenario ? <Link className="badge badge-muted badge-link" key={scenario.id} href={`/scenarios/${scenario.slug}`}>{scenario.name}</Link> : null)}</div></div><div className="project-facts"><div className="project-fact"><span>适合谁</span><strong>{project.suitableFor}</strong></div><div className="project-fact"><span>预计时长</span><strong>{project.duration}</strong></div><div className="project-fact"><span>开始前需要</span><strong>{project.prerequisites.join('；')}</strong></div><div className="project-fact"><span>最终产出</span><strong>{project.expectedOutput}</strong></div></div></div></section>
    <div className="page-container"><section className="detail-block"><div className="detail-layout"><div className="reading-column"><SectionHeading eyebrow="01 / 你要解决的问题" title="从问题开始，而不是从工具开始" /><p>{project.summary}</p><div className="card-grid card-grid-2 section-gap-top"><article className="side-card"><strong>涉及能力</strong><div className="relation-list">{capabilityLabels.map((capability) => capability ? <Link key={capability.id} href={`/capabilities/${capability.slug}`}>{capability.name}</Link> : null)}</div></article><article className="side-card"><strong>应用场景</strong><div className="relation-list">{scenarioLabels.map((scenario) => scenario ? <Link key={scenario.id} href={`/scenarios/${scenario.slug}`}>{scenario.name}</Link> : null)}</div></article></div><SectionHeading eyebrow="02 / 体验步骤" title="完成一个小成果，需要经过哪些交接" /><ol className="project-step-list">{project.steps.map((step) => <li key={step}>{step}</li>)}</ol></div><aside className="side-panel"><div className="side-card"><strong>先看资源状态</strong><StatusBadge status={project.resourceHealth.status} label={{ available: '资源可用', degraded: '资源有替代入口', unverified: '待人工核验', unavailable: '资源暂不可用' }[project.resourceHealth.status]} /><p>{project.resourceHealth.note ?? '官方资源跳转前，先确认数据访问级别、许可和工具成本。'}</p><ArrowLink href={`/projects/${project.slug}/resources`}>查看资源与替代入口</ArrowLink></div><div className="boundary-card"><strong>适用边界</strong><p>{project.boundary}</p></div></aside></div></section>
      <section className="detail-block"><SectionHeading eyebrow="03 / 形成证据" title="你最后应该留下什么" /><div className="card-grid card-grid-3"><article className="side-card"><Badge tone="blue">产物</Badge><h3 className="detail-card-heading project-heading">{project.expectedOutput}</h3><p>可以是截图、Notebook、判断表、短报告或系统图，由你自行保存。</p></article><article className="side-card"><Badge tone="teal">验证</Badge><h3 className="detail-card-heading project-heading">共同验收标准</h3><p>{project.validation}</p></article><article className="side-card"><Badge tone="amber">下一步</Badge><h3 className="detail-card-heading project-heading">继续迁移</h3><p>{project.nextStep}</p></article></div>{project.courseEvidence.length > 0 ? <div className="callout"><p><strong>课程证据：</strong>{courseEvidence.map((evidence) => `${evidence.major?.shortName ?? evidence.majorId}：${evidence.course}`).join('；')}</p></div> : null}</section>
      {project.mode === 'cross-major' ? <section className="detail-block"><SectionHeading eyebrow="04 / 协作接口" title="两种专业怎样交接输入、输出和验收" description="角色只是能力匹配建议，不限制学生跨专业承担任务，也不等同于就业岗位推荐。" /><div className="card-grid card-grid-2">{project.collaborationRoles.map((role) => <article className="side-card" key={role.id}><Badge tone={role.suggestedMajorIds.includes('major-bme') ? 'teal' : 'blue'}>{role.title}</Badge><p><strong>职责：</strong>{role.responsibilities.join('；')}</p><p><strong>输入：</strong>{role.inputs.join('；')}</p><p><strong>输出：</strong>{role.outputs.join('；')}</p><p><strong>验收：</strong>{role.acceptance.join('；')}</p></article>)}</div></section> : null}
      <section className="detail-block"><SectionHeading eyebrow="05 / 数据与工具" title="打开外部教程前，先核对这些信息" /><div className="comparison-table-wrap"><table className="comparison-table"><caption className="sr-only">项目工具、数据和许可</caption><tbody><tr><th scope="row">工具 / 材料</th><td><ul className="detail-list list-no-top">{project.tools.map((tool) => <li key={tool.name}><a className="text-link" href={tool.officialUrl} target="_blank" rel="noreferrer">{tool.name} <span aria-hidden="true">↗</span></a></li>)}</ul></td></tr><tr><th scope="row">数据类型</th><td>{siteConfig.projectDataLabels.kind[project.data.kind]} · {siteConfig.projectDataLabels.sensitivity[project.data.sensitivity]}</td></tr><tr><th scope="row">数据访问</th><td>{project.dataAccess}（{siteConfig.projectDataLabels.access[project.data.access]}）</td></tr><tr><th scope="row">数据来源</th><td>{project.dataSource}</td></tr><tr><th scope="row">许可</th><td>{project.license}</td></tr></tbody></table></div></section>
      <section className="detail-block"><div className="callout"><p><strong>跨专业协作提示：</strong>{project.majorIds.length > 1 ? '这张卡要求两种专业透镜交接输入、输出和共同验收，不要把它拆成两个互不相干的答案。' : '你可以先从一个专业透镜开始，再回到能力地图查看另一种专业视角如何补充。'}</p></div><SourceLine source={source} label="项目来源" /></section>
    </div>
  </>;
}
